export interface ProductItem {
    id: string,
    name: string,
    price: number,
    src: string,
    quantity: number,
    added: boolean,
}

const InitialState: ProductItem[] = [
    {
        id: "0",
        name: "Air Jordan 3 Retro SE",
        src: "https://i.ibb.co/25HRvwC/Air-Jordan-3.png",
        price: 200,
        quantity: 0,
        added: false,
    },
    {
        id: "1",
        name: "Air Jordan XXXIV Low",
        src: "https://i.ibb.co/6yfZfgP/air-jordan-xxxiv.png",
        price: 175,
        quantity: 0,
        added: false,
    },
    {
        id: "2",
        name: "Air Jordan 1 Low SE",
        src: "https://i.ibb.co/pLDdrZr/air-jordan-1.png",
        price: 290,
        quantity: 0,
        added: false,
    },
    {
        id: "3",
        name: "Air Jordan 14 Retro",
        src: "https://i.ibb.co/hKbcnXX/air-jordan-14-retro.png",
        price: 310,
        quantity: 0,
        added: false,
    },
    {
        id: "4",
        name: "Air Jordan 1 Mid",
        src: "https://i.ibb.co/HV7w4CH/air-jordan-1-mid-women.png",
        price: 215,
        quantity: 0,
        added: false,
    },
    {
        id: "5",
        name: "Air Jordan 1",
        src: 'https://i.ibb.co/TcY35bf/air-jordan-1-low-shoe.png',
        price: 190,
        quantity: 0,
        added: false,
    },
    {
        id: "6",
        name: "Air Jordan 1 Low",
        src: "https://i.ibb.co/9n135Bf/air-jordan-1-low.png",
        price: 214,
        quantity: 0,
        added: false,
    },
    {
        id: "7",
        name: "Air Jordan 1 Mid",
        src: "https://i.ibb.co/fXtWDCJ/air-jordan-1-mid.png",
        price: 340,
        quantity: 0,
        added: false,
    },
    {
        id: "8",
        name: "Jordan Delta",
        src: "https://i.ibb.co/WV7pM3W/jordan-delta.png",
        price: 400,
        quantity: 0,
        added: false,
    },
    {
        id: "9",
        name: "Air Jordan 1 Mid SE",
        src: "https://i.ibb.co/ZWNLMvP/air-jordan-1-mid-se.png",
        price: 395,
        quantity: 0,
        added: false,
    },
    {
        id: "10",
        name: "Air Jordan OG",
        src: "https://i.ibb.co/QbN4rRW/air-jordan-og.png",
        price: 150,
        quantity: 0,
        added: false,
    },
    {
        id: "11",
        name: "Air Jordan 2 Retro",
        src: "https://i.ibb.co/w4PvRS6/air-jordan-2-retro.png",
        price: 215,
        quantity: 0,
        added: false,
    },
]
export { InitialState }

